[package]
name = "hctr2"
version = "0.3.0"
description = """
An implementation of the length-preserving encryption HCTR2 algorithm.
"""
authors = ["Eric Lagergren"]
edition = "2021"
license = "BSD-3-Clause"
readme = "README.md"
documentation = "https://docs.rs/hctr2-rs"
repository = "https://github.com/ericlagergren/hctr2-rs"
keywords = [ "hctr2" ]
categories = [ "cryptography", "no-std", "no-std::no-alloc" ]

[features]
default = [
	"aes",
	# "zeroize",
]

# Enable optimized `aes` implementations.
aes = [
	"dep:aes",

	"polyval",
]

# Enable dangerous cryptpgraphic primitives.
hazmat = []

# Enable the POLYVAL polynomial in GF(2¹²⁸).
polyval = ["dep:polyhash"]

# Force the software implementations.
soft = []

std = [
	"zeroize?/std",
]

# Enable zeroize support.
zeroize = [
	"dep:zeroize",

	"aes?/zeroize",
	"polyhash?/zeroize",
]

[dependencies]
aes = { version = "0.8", default-features = false, features = ["hazmat"], optional = true }
cfg-if = { version = "1", default-features = false }
generic-array = { version = "1.1", default-features = false }
polyhash = { version = "0.1", path = "/Users/eric/git/polyval-rs", optional = true }
typenum = { version = "1.17" }
zeroize = { version = "1.8", default-features = false, optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
cpufeatures = { version = "0.2.14", default-features = false }

[dev-dependencies]
criterion = { version = "0.5" }
hex = { version = "0.4", features = ["serde"] }
pprof = { version = "0.12", features = ["criterion", "flamegraph", "protobuf-codec"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1" }

[[bench]]
name = "lib"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-all-features]
always_include_features = []

denylist = []
